### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:9000

### ISSUE THREAD

**Issue by hckhanh** [Stocard/node-ssh-forward#24]
I really don't know why, buy I always receive:

```console
Error: connect ECONNREFUSED 127.0.0.1:9000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9000
}
```

Even though I set the fromPort and toHost in forward function

**Comment by Junkern** [comment]
Could you post the whole source code and quickly explain what you are trying to accomplish? Without any other information my only guess is that nothing is running on port `9000`

**Comment by hckhanh** [comment]
Sorry for this, I forget to turn on my module. Your package is so amazing.
