### ISSUE TITLE
I am trying to ssh to my server using bastion host but getting timeout error. 

### ISSUE THREAD

**Issue by alokkumar0009** [Stocard/node-ssh-forward#27]
var run = async () => {
				const ssh = new SSHConnection({
					username: 'test1', 
					endHost: 'dev01',
					bastionHost: 'bastion.aws.cloud.uk'
				  })
				  await ssh.executeCommand('uptime')
				}
			  run()

**Comment by Junkern** [comment]
Sorry for the late reply. Do you still encounter that problem?

**Comment by alokkumar0009** [comment]
Yes , still not resolved

**Comment by Junkern** [comment]
My gut feeling tells me, that this is not a problem with my library, but something about your AWS instance security settings. If you use the `ssh` command directly from your command line you should also not be able to connect. Maybe your security groups do not allow any traffic on port 22 on either your bastion host or your endhost? Or the address of your endhost is not correct?

Closing this for now.
