### ISSUE TITLE
SSH2 Critical Vulnerability

### ISSUE THREAD

**Issue by Jose-Matsuda** [Stocard/node-ssh-forward#39]
Hello node-ssh-forward team.

There seems to be a critical vulnerability with one of the packages you are using being
[ "ssh2": "^0.8.9"](https://github.com/Stocard/node-ssh-forward/blob/f908f4e305068ab68dacf2acd30e5ca81c5cbb10/package.json#L10 )

More details at 
https://github.com/advisories/GHSA-652h-xwhf-q4h6

Would someone be able to update the used package to 1.4.0? Thanks!

I see that dependabot has made a pr https://github.com/Stocard/node-ssh-forward/pull/38 to bump it but it failed :(

**Comment by Junkern** [comment]
I think the PR #38 failed, because Stocard does not use Travis anymore? (I am guessing here, because I am not working there anymore). Migration to Github Actions should do the trick here.
But I created PR to bump `ssh2` version #40
